"use client";
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const en = {
  feed: "Feed", trending: "Trending", favorites: "Favorites", settings: "Settings", search: "Search content", searchLabel: "Search news, movies and posts", searchTopicPrefix: "Try", topicClimate: "climate research", topicTechnology: "technology policy", topicCinema: "independent cinema", topicHealth: "public health", account: "Account", results: "Results for", dragHint: "Drag the handle or use the arrows to reorder", loadMore: "Load more", caughtUp: "You're all caught up.", darkMode: "Dark mode", language: "Language", profile: "Profile", signIn: "Sign in", signOut: "Sign out", displayName: "Display name", email: "Email address", savedLocally: "Your profile is stored in this browser only.", switchToLight: "Switch to light mode", switchToDark: "Switch to dark mode", mockSignIn: "Mock sign-in. No password or server account is used.", today: "Today", signInToRead: "Sign in to continue", signInToReadHint: "Sign in to continue to “{{title}}”.", profileReady: "Profile ready", profileReadyHint: "Your local profile is ready. Continue to “{{title}}” when you are ready.", continueToArticle: "Continue to article", localProfileNote: "This demo stores a profile in this browser only. It does not create a server account.", closeDialog: "Close sign-in dialog", imageUnavailable: "Article image unavailable", dateUnavailable: "Date unavailable",
  categories: "Categories", categoriesHint: "Your feed and trending items come from the categories you select.", contentTypes: "Filter by content type", allContent: "All", movies: "Movies", posts: "Posts", noFilteredItems: "No {{type}} items in this feed", chooseAnotherType: "Choose another content type or adjust your followed categories.", profileSettings: "Profile settings", updateProfile: "Update profile", profileUpdated: "Profile updated.", appearance: "Appearance", pickCategory: "Pick at least one category", pickCategoryHint: "Your feed is built from the categories you follow.", noCategories: "No categories selected", chooseCategories: "Choose categories to see what's trending.", openSettings: "Open settings", noResults: "No results for", noResultsHint: "Try a different keyword, or add more categories in settings.", nothingHere: "Nothing here yet", nothingHint: "Add more categories in settings.", failed: "Something went wrong", retry: "Try again", noFavorites: "No favorites yet", noFavoritesHint: "Tap the heart on any card to save it here.", browseFeed: "Browse your feed", readMore: "Read More", playNow: "Play Now", viewPost: "View Post", news: "News", movie: "Movie", post: "Post", moveUp: "Move {{title}} up", moveDown: "Move {{title}} down", addFavorite: "Add {{title}} to favorites", removeFavorite: "Remove {{title}} from favorites", trendingNow: "Trending now", trendingNews: "Trending news", trendingMovies: "Trending movies", trendingPosts: "Trending posts", loading: "Loading", loadingMore: "Loading more", sourceWarning: "{{count}} of {{total}} sources are unavailable right now.", noTrending: "No trending items are available right now.", privacy: "Privacy policy", terms: "Terms and conditions",
  showSidebar: "Show sidebar", hideSidebar: "Hide sidebar", sidebarVisibility: "Show desktop sidebar", feedControls: "Feed controls", feedControlsHint: "Choose how cards respond to horizontal gestures. The buttons remain available when gestures are off.", swipeActions: "Enable card gestures", swipeDirections: "Swipe right to remove a card. Swipe left to see less like it.", recommendLess: "Less like this", recommendLessItem: "Show fewer items like {{title}}", dismissItem: "Remove {{title}} from the feed", remove: "Remove", restore: "Restore", removedItems: "Removed from your feed", lessLikeThisItems: "Show less like these", resetFeedChoices: "Reset all feed choices", noFeedChoices: "Your feed choices will appear here.", dragToReorder: "Drag to reorder {{title}}", hiddenItemsCount: "{{count}} cards hidden by your feed choices.", manageRecommendations: "Manage choices",
};
const es = {
  feed: "Inicio", trending: "Tendencias", favorites: "Guardados", settings: "Ajustes", search: "Buscar contenido", searchLabel: "Buscar noticias, películas y publicaciones", searchTopicPrefix: "Prueba", topicClimate: "investigación climática", topicTechnology: "política tecnológica", topicCinema: "cine independiente", topicHealth: "salud pública", account: "Cuenta", results: "Resultados para", dragHint: "Arrastra el control o usa las flechas para reordenar", loadMore: "Cargar más", caughtUp: "Has visto todo por ahora.", darkMode: "Modo oscuro", language: "Idioma", profile: "Perfil", signIn: "Iniciar sesión", signOut: "Cerrar sesión", displayName: "Nombre para mostrar", email: "Correo electrónico", savedLocally: "Tu perfil solo se guarda en este navegador.", switchToLight: "Cambiar a modo claro", switchToDark: "Cambiar a modo oscuro", mockSignIn: "Acceso de prueba. No se usa contraseña ni cuenta de servidor.", today: "Hoy", signInToRead: "Inicia sesión para continuar", signInToReadHint: "Inicia sesión para continuar a “{{title}}”.", profileReady: "Perfil listo", profileReadyHint: "Tu perfil local está listo. Continúa a “{{title}}” cuando quieras.", continueToArticle: "Continuar al artículo", localProfileNote: "Esta demostración guarda el perfil solo en este navegador. No crea una cuenta en un servidor.", closeDialog: "Cerrar diálogo de acceso", imageUnavailable: "Imagen del artículo no disponible", dateUnavailable: "Fecha no disponible",
  categories: "Categorías", categoriesHint: "Tu inicio y las tendencias se basan en las categorías que eliges.", contentTypes: "Filtrar por tipo de contenido", allContent: "Todo", movies: "Películas", posts: "Publicaciones", noFilteredItems: "No hay contenido de {{type}} en este inicio", chooseAnotherType: "Elige otro tipo de contenido o cambia tus categorías.", profileSettings: "Ajustes del perfil", updateProfile: "Actualizar perfil", profileUpdated: "Perfil actualizado.", appearance: "Apariencia", pickCategory: "Elige al menos una categoría", pickCategoryHint: "Tu inicio se crea con las categorías que sigues.", noCategories: "No hay categorías seleccionadas", chooseCategories: "Elige categorías para ver las tendencias.", openSettings: "Abrir ajustes", noResults: "No hay resultados para", noResultsHint: "Prueba otra palabra o añade categorías en ajustes.", nothingHere: "Todavía no hay contenido", nothingHint: "Añade más categorías en ajustes.", failed: "Algo salió mal", retry: "Reintentar", noFavorites: "Todavía no hay elementos guardados", noFavoritesHint: "Pulsa el corazón de una tarjeta para guardarla aquí.", browseFeed: "Explorar el inicio", readMore: "Leer más", playNow: "Ver ahora", viewPost: "Ver publicación", news: "Noticias", movie: "Película", post: "Publicación", moveUp: "Mover {{title}} hacia arriba", moveDown: "Mover {{title}} hacia abajo", addFavorite: "Guardar {{title}} en favoritos", removeFavorite: "Quitar {{title}} de favoritos", trendingNow: "Tendencias actuales", trendingNews: "Noticias populares", trendingMovies: "Películas populares", trendingPosts: "Publicaciones populares", loading: "Cargando", loadingMore: "Cargando más", sourceWarning: "{{count}} de {{total}} fuentes no están disponibles ahora.", noTrending: "No hay tendencias disponibles ahora.", privacy: "Privacidad", terms: "Términos y condiciones",
  showSidebar: "Mostrar navegación", hideSidebar: "Ocultar navegación", sidebarVisibility: "Mostrar navegación de escritorio", feedControls: "Controles del inicio", feedControlsHint: "Elige cómo responden las tarjetas a los gestos horizontales. Los botones siguen disponibles si desactivas los gestos.", swipeActions: "Activar gestos en tarjetas", swipeDirections: "Desliza a la derecha para quitar una tarjeta. Desliza a la izquierda para ver menos contenido similar.", recommendLess: "Ver menos similares", recommendLessItem: "Ver menos contenido similar a {{title}}", dismissItem: "Quitar {{title}} del inicio", remove: "Quitar", restore: "Restaurar", removedItems: "Quitados del inicio", lessLikeThisItems: "Ver menos similares a", resetFeedChoices: "Restablecer preferencias del inicio", noFeedChoices: "Tus preferencias del inicio aparecerán aquí.", dragToReorder: "Arrastra para reordenar {{title}}", hiddenItemsCount: "{{count}} tarjetas ocultas por tus preferencias.", manageRecommendations: "Administrar preferencias",
};

if (!i18n.isInitialized) i18n.use(initReactI18next).init({ resources: { en: { translation: en }, es: { translation: es } }, lng: "en", fallbackLng: "en", interpolation: { escapeValue: false }, react: { useSuspense: false } });
export default i18n;
